# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920f8970b851c5abf5db8c6578c17e94878756156768f577e7a9002f6db3e17428fb87ce7cf26bc08f87566f390966efb0a4c614793291a1df1429847dc6a32f

test:
  secret_key_base: f50b74f5fcd901ff5b633cae051a054ea0a911918c041def489267a7efbf05ebd11a91dca720868109f20b85a18ccbdc753c353f4326a4e83c80da1ad2c04262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
