# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ef060370f4d816f0df9a5ddb1724f3972a9483640fc5a2c14ed9ee655057458b7876f7cea28b8498bf2a1f68d98d421ca86116115e49e1f755a135e47d5ee1

test:
  secret_key_base: 04312234a461ff7ee17b12b1ba257f8e9a6252b29477d1647f4e6155ccde3f7d9a459a57a0fd07206ec0fb2572580c6f2730ec388a2c2fe2d4bf3656be98d9c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
